# Generated by Django 4.1.1 on 2023-11-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificate_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
