# Generated by Django 4.1.1 on 2023-11-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_alter_certificate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='full_name',
        ),
    ]
